### ISSUE TITLE
ERROR: Service 'mysql' failed to build

### ISSUE THREAD

**Issue by haohonglong** [liufee/docker-compose#1]
这个错误该怎么处理？

Building mysql
Step 1/12 : FROM centos:latest
 ---> 0f3e07c0138f
Step 2/12 : MAINTAINER liufee job@feehi.com
 ---> Using cache
 ---> 0497cb413219
Step 3/12 : ARG MYSQL_VER=5.7.21
 ---> Using cache
 ---> 247179699688
Step 4/12 : ARG MYSQL_DATA_DIR=/data/mysql
 ---> Using cache
 ---> 5a23be7d4667
Step 5/12 : ARG MYSQL_PID_DIR=/var/run/mysql
 ---> Using cache
 ---> 36741b21ddf2
Step 6/12 : ARG MYSQL_LOG_DIR=/var/log/mysql
 ---> Using cache
 ---> fd6b03a7af5f
Step 7/12 : ARG MYSQL_SOCK_DIR=/var/lib/mysql
 ---> Using cache
 ---> 834163e8768b
Step 8/12 : RUN yum install -y gcc-c++ gcc make automake cmake ncurses-devel bison bison-devel
 ---> Running in 09030510bcd9
CentOS-8 - AppStream                            348 kB/s | 6.3 MB     00:18    
CentOS-8 - Base                                 207 kB/s | 7.9 MB     00:39    
CentOS-8 - Extras                               493  B/s | 2.1 kB     00:04    
No match for argument: bison-devel
Error: Unable to find a match
ERROR: Service 'mysql' failed to build: The command '/bin/sh -c yum install -y gcc-c++ gcc make automake cmake ncurses-devel bison bison-devel' returned a non-zero code: 1

**Comment by liufee** [comment]
把os版本改成7.0，centos高版本没有这个源
